# Generated by Django 3.1.1 on 2020-09-29 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('idCultivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nombreCientifico', models.CharField(max_length=200)),
                ('descripción', models.CharField(max_length=10000)),
                ('imagen', models.CharField(max_length=1000)),
                ('ambienteCrecimiento', models.CharField(max_length=200)),
                ('variedadesCultivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('idEnfermedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nombreCientifico', models.CharField(max_length=200)),
                ('descripción', models.CharField(max_length=10000)),
                ('imagen', models.CharField(max_length=1000)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cultivo')),
            ],
        ),
    ]
