# Generated by Django 3.1.1 on 2020-09-30 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200929_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='PasosTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noPaso', models.CharField(max_length=10)),
                ('descripción', models.CharField(max_length=1000)),
                ('Tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tratamiento')),
            ],
        ),
    ]
