# Generated by Django 3.1.1 on 2020-09-30 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_pasostratamiento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasostratamiento',
            name='urlImagen',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TablaImagenTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=10000)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='TablaImagenEnfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=10000)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='TablaImagenCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=10000)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cultivo')),
            ],
        ),
    ]
