# Generated by Django 3.1.1 on 2020-09-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20200929_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioForo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('contrasena', models.CharField(max_length=16)),
                ('dedicacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaForo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.CharField(max_length=500)),
                ('apropiada', models.BooleanField(verbose_name=True)),
                ('usuarioForo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuarioforo')),
            ],
        ),
    ]
