# Generated by Django 3.1 on 2020-10-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_respuestaforo_sugerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='variedadesCultivo',
        ),
    ]
