# Generated by Django 3.1 on 2020-10-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20201007_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danosCultivo', models.CharField(max_length=500)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cultivo')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.enfermedad')),
            ],
        ),
        migrations.AddField(
            model_name='respuestaforo',
            name='pregunta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='principal.preguntaforo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TratamientoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.preguntaforo')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='TablaImagenEnfermedadCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlImagen', models.CharField(max_length=500)),
                ('enfermedadCultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.enfermedadcultivo')),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.enfermedad')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.preguntaforo')),
            ],
        ),
        migrations.CreateModel(
            name='CultivoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cultivo')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.preguntaforo')),
            ],
        ),
    ]
