# Generated by Django 3.1 on 2020-10-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20201007_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='enfermedad',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tablaimagencultivo',
            old_name='URL',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='enfermedad',
            name='dañosCultivo',
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='danosCultivo',
            field=models.CharField(db_column='danos_cultivo', default=None, max_length=500),
            preserve_default=False,
        ),
    ]
