# Generated by Django 3.1 on 2020-10-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20201008_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='enfermedad',
            name='imagen',
        ),
    ]
