# Generated by Django 3.1 on 2020-10-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20201008_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='danosCultivo',
            field=models.CharField(max_length=500),
        ),
    ]
