# Generated by Django 3.1 on 2020-10-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_remove_enfermedad_danoscultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedad',
            name='descripcion',
        ),
    ]
