# Generated by Django 3.1 on 2020-10-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_remove_enfermedad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='descripcion',
            field=models.CharField(default=None, max_length=10000),
            preserve_default=False,
        ),
    ]
