# Generated by Django 3.1 on 2020-10-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20201011_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedadcultivo',
            name='danosCultivo',
        ),
    ]
