# Generated by Django 3.1 on 2020-10-28 10:52

import aplicaciones.principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20201014_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaimagenenfermedad',
            name='URL',
        ),
        migrations.AddField(
            model_name='tablaimagencultivo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=aplicaciones.principal.models.TablaImagenCultivo.cargar_imagen_cultivo),
        ),
        migrations.AddField(
            model_name='tablaimagenenfermedad',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=aplicaciones.principal.models.TablaImagenEnfermedad.cargar_imagen_enfermedad),
        ),
    ]
