# Generated by Django 3.1 on 2020-10-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_remove_tablaimagencultivo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedadpregunta',
            name='enfermedad',
        ),
    ]
