# Generated by Django 3.1 on 2020-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_remove_enfermedadpregunta_enfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango',
            name='rangoMaximo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rango',
            name='rangoMinimo',
            field=models.IntegerField(),
        ),
    ]
