# Generated by Django 3.1 on 2020-11-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_auto_20201102_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
