# Generated by Django 3.1 on 2020-11-04 01:11

import aplicaciones.principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_auto_20201102_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasostratamiento',
            name='urlImagen',
            field=models.ImageField(blank=True, upload_to=aplicaciones.principal.models.PasosTratamiento.cargar_imagen_cultivo),
        ),
    ]
