# Generated by Django 3.1 on 2020-11-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_auto_20201103_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedadcultivo',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivo', to='principal.cultivo'),
        ),
        migrations.AlterField(
            model_name='enfermedadcultivo',
            name='enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedad', to='principal.enfermedad'),
        ),
    ]
